--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Terpz710/WarzoneEnvoys
build-by-default: true
branches:
- stable
- legacy
projects:
  WarzoneEnvoys:
    path: ""
    libs:
      - src: DaPigGuy/libPiggyUpdateChecker/libPiggyUpdateChecker
        version: ^1.0.0
    lint: false
...
