# Made by Terpz710

# Time that chest will spawn.
target_time: 60

# Certain amount of items a chest can have
items_per_chest:
  min: 1
  max: 5

# Where envoys will spawn
chest_locations:
  - world: "world"
    x: 10
    y: 64
    z: 10
  - world: "world"
    x: 20
    y: 64
    z: 20
