# Made by Terpz710

# An example on how to add envoys
#  chest_locations:
#    - world: "Warzone"
#      x: -10
#      y: 20
#      z: -54
#    - world: "Warzone"
#      x: -87
#      y: 20
#      z: 34

# Time before the envoy spawn
# In seconds not ticks
# 1 = 1second
# 60 = 1minute
target_time: 60

# Random amount of items that a envoy can have
# For example the min is "1" and the max is "5"
# There is a chance for the envoy to spawn in with
# 2 items from the list or 4 but never 0 items and it will never exceed the max limit
items_per_chest:
  min: 1
  max: 5

# Envoy configuration
# Take a look on top for an example on how to add
# Envoys to your world
# You can set unlimited of envoys
chest_locations:
  - world: "world"
    x: 10
    y: 64
    z: 10
  - world: "world"
    x: 20
    y: 64
    z: 20
