# Made by Terpz710

# Time that chest will spawn.
target_time: 30

# Despawn timer
chest_despawn_time: 60

chest_locations:
  - world: "world"
    x: 10
    y: 64
    z: 10
  - world: "world"
    x: 20
    y: 64
    z: 20
